//CNCT = ColumnNameChangeTable
let fn_CNCT = (tbl as table) =>
    Table.RemoveColumns(Table.AddColumn(Record.ToTable(tbl{2}), "NewName", each Text.BeforeDelimiter([Value],":")),"Value")
in  fn_CNCT

//Add index
//delete rows that dont need changing - pop up message
