= Table.AddColumn(Source, "Custom", each Text.Select([pyx_vehiclename],{"0".."9"}))
